//
//  Entry+CoreDataClass.swift
//  Journal
//
//  Created by Owais Quadri on 2023-07-03.
//
// This file was created by selecting Entry in the coredata file, then in the right tab: codegen = manual/none, and Editor>Create NSManagedObject ...
// DO NOT EDIT THIS FILE

import Foundation
import CoreData

@objc(Entry)
public class Entry: NSManagedObject {

}
